name: Lint Files
"on": push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
              pnpm install --frozen-lockfile
              pnpm build
              pnpm lint
